<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Petstore\Endpoint;

class DeleteUser extends \Petstore\Runtime\Client\BaseEndpoint implements \Petstore\Runtime\Client\Endpoint
{
    use \Petstore\Runtime\Client\EndpointTrait;
    protected $username;

    /**
     * This can only be done by the logged in user.
     *
     * @param string $username The name that needs to be deleted
     */
    public function __construct(string $username)
    {
        $this->username = $username;
    }

    public function getMethod(): string
    {
        return 'DELETE';
    }

    public function getUri(): string
    {
        return str_replace(['{username}'], [$this->username], '/user/{username}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    /**
     * @return null
     *
     * @throws \Petstore\Exception\DeleteUserBadRequestException
     * @throws \Petstore\Exception\DeleteUserNotFoundException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (400 === $status) {
            throw new \Petstore\Exception\DeleteUserBadRequestException($response);
        }
        if (404 === $status) {
            throw new \Petstore\Exception\DeleteUserNotFoundException($response);
        }
    }

    public function getAuthenticationScopes(): array
    {
        return [];
    }
}
