<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Petstore\Endpoint;

class UpdatePetWithForm extends \Petstore\Runtime\Client\BaseEndpoint implements \Petstore\Runtime\Client\Endpoint
{
    use \Petstore\Runtime\Client\EndpointTrait;
    protected $petId;
    protected $accept;

    /**
     * Updates a pet resource based on the form data.
     *
     * @param int   $petId           ID of pet that needs to be updated
     * @param array $queryParameters {
     *
     * @var string $name Name of pet that needs to be updated
     * @var string $status Status of pet that needs to be updated
     *             }
     *
     * @param array $accept Accept content header application/json|application/xml
     */
    public function __construct(int $petId, array $queryParameters = [], array $accept = [])
    {
        $this->petId = $petId;
        $this->queryParameters = $queryParameters;
        $this->accept = $accept;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return str_replace(['{petId}'], [$this->petId], '/pet/{petId}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        if (empty($this->accept)) {
            return ['Accept' => ['application/json', 'application/xml']];
        }

        return $this->accept;
    }

    protected function getQueryOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['name', 'status']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults([]);
        $optionsResolver->addAllowedTypes('name', ['string']);
        $optionsResolver->addAllowedTypes('status', ['string']);

        return $optionsResolver;
    }

    /**
     * @return \Petstore\Model\Pet|null
     *
     * @throws \Petstore\Exception\UpdatePetWithFormBadRequestException
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'Petstore\Model\Pet', 'json');
        }
        if (400 === $status) {
            throw new \Petstore\Exception\UpdatePetWithFormBadRequestException($response);
        }

        return null;
    }

    public function getAuthenticationScopes(): array
    {
        return ['petstore_auth'];
    }
}
