<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Petstore\Model;

class Order extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $id;
    /**
     * @var int
     */
    protected $petId;
    /**
     * @var int
     */
    protected $quantity;
    /**
     * @var \DateTime
     */
    protected $shipDate;
    /**
     * Order Status.
     *
     * @var string
     */
    protected $status;
    /**
     * @var bool
     */
    protected $complete;

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getPetId(): int
    {
        return $this->petId;
    }

    public function setPetId(int $petId): self
    {
        $this->initialized['petId'] = true;
        $this->petId = $petId;

        return $this;
    }

    public function getQuantity(): int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->initialized['quantity'] = true;
        $this->quantity = $quantity;

        return $this;
    }

    public function getShipDate(): \DateTime
    {
        return $this->shipDate;
    }

    public function setShipDate(\DateTime $shipDate): self
    {
        $this->initialized['shipDate'] = true;
        $this->shipDate = $shipDate;

        return $this;
    }

    /**
     * Order Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Order Status.
     */
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }

    public function getComplete(): bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->initialized['complete'] = true;
        $this->complete = $complete;

        return $this;
    }
}
