<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Petstore\Model;

class Pet extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int
     */
    protected $id;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var Category
     */
    protected $category;
    /**
     * @var list<string>
     */
    protected $photoUrls;
    /**
     * @var list<Tag>
     */
    protected $tags;
    /**
     * pet status in the store.
     *
     * @var string
     */
    protected $status;

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    public function getCategory(): Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->initialized['category'] = true;
        $this->category = $category;

        return $this;
    }

    /**
     * @return list<string>
     */
    public function getPhotoUrls(): array
    {
        return $this->photoUrls;
    }

    /**
     * @param list<string> $photoUrls
     */
    public function setPhotoUrls(array $photoUrls): self
    {
        $this->initialized['photoUrls'] = true;
        $this->photoUrls = $photoUrls;

        return $this;
    }

    /**
     * @return list<Tag>
     */
    public function getTags(): array
    {
        return $this->tags;
    }

    /**
     * @param list<Tag> $tags
     */
    public function setTags(array $tags): self
    {
        $this->initialized['tags'] = true;
        $this->tags = $tags;

        return $this;
    }

    /**
     * pet status in the store.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * pet status in the store.
     */
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }
}
